from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ModelHyperparameters:
    bivariate_correlation_base: float = 0.08
    bivariate_correlation_cap: float = 0.10
    bivariate_shared_goal_share: float = 0.18
    bivariate_closeness_bonus: float = 0.04
    bivariate_knockout_bonus: float = 0.03
    bivariate_importance_bonus: float = 0.02
    low_score_draw_threshold: float = 0.27
    low_score_draw_positive_cap: float = 0.12
    low_score_draw_negative_cap: float = -0.08
    low_score_rho_base: float = -0.16
    low_score_rho_positive_draw: float = -0.55
    low_score_rho_negative_draw: float = 0.20
    low_score_knockout_shift: float = -0.02
    low_score_floor: float = 0.05
    model_contrast_weight: float = 0.18
    model_low_score_base: float = 0.12
    model_low_score_closeness_weight: float = 0.08
    model_low_score_draw_weight: float = 0.45
    model_low_score_knockout_bonus: float = 0.03
    model_low_score_min: float = 0.12
    model_low_score_max: float = 0.28
    model_overdispersed_base: float = 0.08
    model_overdispersed_total_weight: float = 0.08
    model_overdispersed_draw_penalty: float = 0.05
    model_overdispersed_max: float = 0.18
    model_ml_base: float = 0.10
    model_ml_total_weight: float = 0.04
    model_ml_closeness_weight: float = 0.03
    model_ml_market_weight: float = 0.03
    model_ml_knockout_bonus: float = 0.02
    model_ml_max: float = 0.17
    ml_total_market_blend: float = 0.10
    ml_favorite_share_weight: float = 0.08
    ml_market_edge_weight: float = 0.12
    ml_knockout_total_guard: float = 0.06
    ml_high_total_boost: float = 0.05
    ml_score_shape_strength: float = 0.12
    negative_binomial_alpha_base: float = 0.12
    negative_binomial_alpha_total_weight: float = 0.06
    negative_binomial_alpha_closeness_weight: float = 0.03
    negative_binomial_alpha_knockout_penalty: float = 0.02
    model_primary_min: float = 0.40
    model_market_bonus_strength: float = 0.30
    model_consensus_strength: float = 1.0
    market_shrink_disagreement_boost: float = 0.55
    market_shrink_gap_boost: float = 0.70
    market_shrink_cap: float = 0.48
    outcome_temperature_strength: float = 0.32
    outcome_temperature_sharpen: float = 0.08
    outcome_temperature_flatten: float = 0.10
    outcome_temperature_min: float = 0.90
    outcome_temperature_max: float = 1.12
    goal_consensus_base_weight: float = 0.18
    goal_consensus_high_gap_weight: float = 0.34
    goal_consensus_extreme_gap_weight: float = 0.46
    goal_consensus_high_gap: float = 0.45
    goal_consensus_extreme_gap: float = 0.75
    goal_consensus_total_offset: float = 0.03
    confidence_base: float = 0.10
    confidence_top_outcome_weight: float = 0.60
    confidence_gap_weight: float = 0.25
    confidence_top3_weight: float = 0.10
    confidence_entropy_weight: float = 0.10
    confidence_agreement_weight: float = 0.12
    confidence_floor: float = 0.05
    confidence_cap: float = 0.99
    extra_time_share: float = 0.29
    extra_time_fatigue_weight: float = 0.16
    extra_time_availability_weight: float = 0.10
    extra_time_attack_form_weight: float = 0.08
    extra_time_recent_form_weight: float = 0.04
    cache_goal_precision: float = 50.0
    cache_rho_precision: float = 100.0
    temporal_cv_fold_size: int = 8
    auto_parallel_min_iterations: int = 4000
    auto_parallel_max_workers_floor: int = 1
    expected_goal_elo_divisor: float = 340.0
    expected_goal_fifa_weight: float = 0.08
    expected_goal_history_strength_weight: float = 0.08
    expected_goal_attack_edge_weight: float = 0.78
    knockout_favorite_share_shrink: float = 0.08


PARAMS = ModelHyperparameters()
MIN_MONTE_CARLO_ITERATIONS = 15000
