from .bracket import BRACKET_MATCH_TITLES, KNOCKOUT_MATCHES, LOSER_NEXT_MATCH, R32_MATCHES, WINNER_NEXT_MATCH
from .confederations import (
    DISCIPLINE_BY_CONFEDERATION,
    HISTORICAL_BY_CONFEDERATION,
    RESOURCE_BY_CONFEDERATION,
    TEMPO_BY_CONFEDERATION,
    TRAVEL_BY_CONFEDERATION,
)
from .overrides import COACH_OVERRIDES, DISCIPLINE_OVERRIDES, RESOURCE_OVERRIDES, TRADITION_BONUS, WORLD_CUP_TITLES
from .rivalries import RIVALRIES, TEAM_NAME_ALIASES
from .stages import GROUP_MATCH_PAIRS, STAGE_ALIASES, STAGE_IMPORTANCE

__all__ = [
    "BRACKET_MATCH_TITLES",
    "COACH_OVERRIDES",
    "DISCIPLINE_BY_CONFEDERATION",
    "DISCIPLINE_OVERRIDES",
    "GROUP_MATCH_PAIRS",
    "HISTORICAL_BY_CONFEDERATION",
    "KNOCKOUT_MATCHES",
    "LOSER_NEXT_MATCH",
    "RESOURCE_BY_CONFEDERATION",
    "RESOURCE_OVERRIDES",
    "R32_MATCHES",
    "RIVALRIES",
    "STAGE_ALIASES",
    "STAGE_IMPORTANCE",
    "TEAM_NAME_ALIASES",
    "TEMPO_BY_CONFEDERATION",
    "TRADITION_BONUS",
    "TRAVEL_BY_CONFEDERATION",
    "WINNER_NEXT_MATCH",
    "WORLD_CUP_TITLES",
]
