RIVALRIES = {
    frozenset({"Argentina", "Brazil"}): 0.16,
    frozenset({"England", "Scotland"}): 0.14,
    frozenset({"Mexico", "United States"}): 0.15,
    frozenset({"Croatia", "Serbia"}): 0.12,
    frozenset({"Japan", "South Korea"}): 0.10,
    frozenset({"Turkey", "Greece"}): 0.10,
}

TEAM_NAME_ALIASES = {
    "espana": "Spain",
    "uruguay": "Uruguay",
    "estadosunidos": "United States",
    "eeuu": "United States",
    "usa": "United States",
    "holanda": "Netherlands",
    "paisesbajos": "Netherlands",
    "brasil": "Brazil",
    "alemania": "Germany",
    "inglaterra": "England",
    "escocia": "Scotland",
    "suiza": "Switzerland",
    "coreadelsur": "South Korea",
    "corearepublica": "South Korea",
    "surcorea": "South Korea",
    "corea": "South Korea",
    "japon": "Japan",
    "arabiasaudita": "Saudi Arabia",
    "nuevazelanda": "New Zealand",
    "costademarfil": "Ivory Coast",
    "caboverde": "Cape Verde",
    "marruecos": "Morocco",
    "argelia": "Algeria",
    "egipto": "Egypt",
    "turquia": "Turkey",
    "turkiye": "Turkey",
    "republicacheca": "Czech Republic",
    "chequia": "Czech Republic",
    "czechia": "Czech Republic",
    "irlanda": "Republic of Ireland",
    "irlandadelnorte": "Northern Ireland",
    "bosnia": "Bosnia and Herzegovina",
    "bosniaherzegovina": "Bosnia and Herzegovina",
    "bosniayherzegovina": "Bosnia and Herzegovina",
    "congord": "Dem. Rep. of Congo",
    "congodr": "Dem. Rep. of Congo",
    "drcongo": "Dem. Rep. of Congo",
    "rdcongo": "Dem. Rep. of Congo",
    "iriran": "Iran",
    "irak": "Iraq",
}
