GROUP_MATCH_PAIRS = [
    (0, 3),
    (1, 2),
    (0, 2),
    (3, 1),
    (0, 1),
    (2, 3),
]

STAGE_IMPORTANCE = {
    "group": 1.00,
    "round32": 1.12,
    "round16": 1.22,
    "quarterfinal": 1.30,
    "semifinal": 1.38,
    "third_place": 1.24,
    "final": 1.48,
}

STAGE_ALIASES = {
    "group": "group",
    "groups": "group",
    "fase_de_grupos": "group",
    "fasegrupos": "group",
    "round32": "round32",
    "round_of_32": "round32",
    "roundof32": "round32",
    "dieciseisavos": "round32",
    "round16": "round16",
    "round_of_16": "round16",
    "roundof16": "round16",
    "octavos": "round16",
    "round8": "quarterfinal",
    "round_of_8": "quarterfinal",
    "roundof8": "quarterfinal",
    "quarterfinal": "quarterfinal",
    "quarterfinals": "quarterfinal",
    "cuartos": "quarterfinal",
    "round4": "semifinal",
    "round_of_4": "semifinal",
    "roundof4": "semifinal",
    "semifinal": "semifinal",
    "semifinals": "semifinal",
    "semis": "semifinal",
    "third_place": "third_place",
    "thirdplace": "third_place",
    "third-place": "third_place",
    "third_and_fourth_place": "third_place",
    "thirdandfourthplace": "third_place",
    "final": "final",
}
